image: node:14-stretch

stages:
  - lint
  - prerequisites
  - build
  - deploy infrastructure
  - deploy services
  - post deploy
  - cleanup

include:
  - local: '/ci/base-configuration.yml'
  - local: '/ci/job-templates.yml'

ESLint:
  stage: lint
  cache:
    policy: pull-push
  script:
    - lerna run lint

prerequisites:
  stage: prerequisites
  extends: .deploy
  variables:
    PACKAGE: prerequisites

certificate:
  stage: prerequisites
  extends: .deploy
  variables:
    PACKAGE: certificate

build website:
  stage: build
  extends: .build
  variables:
    PACKAGE: website

build api:
  stage: build
  extends: .build-with-docker
  variables:
    PACKAGE: api

deploy infrastructure:
  stage: deploy infrastructure
  extends: .deploy
  variables:
    PACKAGE: infrastructure
  needs:
    - 'prerequisites'

deploy cognito trigger:
  stage: deploy services
  extends: .deploy
  variables:
    PACKAGE: cognito-trigger
  needs:
    - 'deploy infrastructure'

deploy api:
  stage: deploy services
  extends: .deploy
  variables:
    PACKAGE: api
  needs:
    - 'deploy infrastructure'
    - 'build api'

deploy website:
  stage: deploy services
  extends: .deploy
  variables:
    PACKAGE: website
  needs:
    - 'build website'

migrations pipeline:
  stage: deploy services
  extends: .deployment-environments
  trigger:
    include: /ci/migrations-pipeline.yml
  needs:
    - 'deploy infrastructure'

#invalidate website cache:
#  stage: post deploy
#  extends: .deployment-environments
#  script: aws cloudfront create-invalidation --distribution-id <DISTRIBUTION_ID> --paths "/*"

cleanup pipeline:
  stage: cleanup
  extends: .deployment-environments
  when: manual
  trigger:
    include: /ci/remove-environment-pipeline.yml
